version: '3.4'
services:
  php-fpm:
    image: php-elastica-fast-populate
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-php
    restart: unless-stopped
    user: "${DUID:-0}:${DGID:-0}"
    volumes:
      - ./:/var/www/html
      - ~/.cache:/.cache
      - ~/.config:/.config
      - ~/.composer:/.composer
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: >-
        idekey=PHPSTORM
        log_level=0
        client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=elastica-fast-populate-docker
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    hostname: mongodb
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: elastica_fast_populate
      MONGO_INITDB_ROOT_PASSWORD: elastica_fast_populate
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "7985:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: inpi_rne
      ME_CONFIG_MONGODB_ADMINPASSWORD: inpi_rne
    depends_on:
      - mongodb
  elasticsearch:
    image: elasticsearch:8.3.3
    restart: unless-stopped
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    deploy:
      resources:
        limits:
          memory: "512M"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  cerebro:
    image: yannart/cerebro:latest
    restart: unless-stopped
    ports:
      - "7984:9000"

volumes:
  postgresql_data:
  pgadmin_data:
  mongodb_data_container:
  elasticsearch:
